sudo: required
dist: trusty
language: node_js
node_js:
- 8.11.1
before_script:
- echo -e "Host fgpv.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- "./scripts/travis/build.sh"
before_install:
- AZ_REPO=$(lsb_release -cs)
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO
  main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install apt-transport-https azure-cli
cache:
  directories:
  - node_modules
  - features/node_modules
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/travis/deploy-build-azure.sh
  on:
    all_branches: true
- provider: script
  skip_cleanup: true
  script: bash ./scripts/travis/docs.sh
  on:
    all_branches: true
    repo: fgpv-vpgf/fgpv-vpgf
    condition: $TRAVIS_BRANCH =~ ^develop$|^ghpages-docs$|^master$|^v\d
    condition: $mProc == dev
- provider: pages
  target_branch: gh-pages
  local-dir: gh-page-files
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    all_branches: true
    repo: fgpv-vpgf/fgpv-vpgf
    condition: $TRAVIS_BRANCH =~ ^develop$|^ghpages-docs$|^master$|^v\d
    condition: $mProc == dev
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/18575ac051d21e4340b1
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: lXPqjmUmxtSl/KWmM1JFeqEKo3Wz+xqo5K/yVQrHNT97Nre0avhfhJXim/QD72aFlZH9Wg2OlLY1gx8zudTh1VDY9gIAPRN9GEvM1hpn+3sWT5GcCkZt3bYzrSMYBq/cadYG9r9LT5pZ8FZ3ZUHUTtsIKzDgVNQXig93cO6hBRweK4dOzshShWaxxs6aEG2wwfmXNcCKUf2pwl1y/4gPPTC30DMWSBLpvMV4KvE52hrLtl1nIflpYhdSqwj2U3IWzKTh8LXhrUmSqC/sh+Cp0XuQQEhfGjiYEXfVHtlDDdUspnYN4sQBdFQuijCLNzzVWmdGAoT9TEHbGH8hKl45rcW+7G+j/yS+pqU9hzEaipkdsMXoku9zuU95pGr0iK4/R/Ev7U7zZXVGjQpuA7mz/Ykrj6+V68aw2gyrlAZ19K1se2RKs8xCQFtAmlf3jNE69A4X32ewtDECfYJkyeTTucO/02uNfCHgSoYfb63OdEQdinF/3nj8AJfp7Po/JkH6bjIhq2VbpMRG9VxIP6TIUp6708oJj9lvOs35ioKTwAnUnRqn7DFJzRstodKR9mjKGWKAZnLCuMlN0PX8VLt7V2GRvklFq7KTJX5Ossw0xVAbgO28nXXrIIM1w6o40O6+BP2xA8xdiHBSbc0YJ3kXZt4SGSyzy3GvElJe/32c02g=
  - secure: g+AfL9bvx3k5Qo1Q59sAiQdtY3wV2T0w6z0/RynNSBZtMb7inJkjSXpPUgJiVb82Ml/59tX5KNz9kVNCiCtHQWiF5i7azKkRI/bT21y7LW0Ey26348IG0c7///sK2wFlm8nPPOHCSkG/PIzVxsSwRiHMGGYgptBPbuENHGGYGRuVTOGImPAthbTAIO3D5zua8SRqfvWe5jfOmFMmWRxm86mJwwaXXZ0a7kfV+aa5RxCwnF2vsKqbBNXq4ho2PXvHX1CvZE2iX0rjL3KE+TgdBmIYainL0/Sy1zOjxnhSWfSle1j0NUTAMMsDQXk7kibfmW9HWZAgov6cFCDivAcrvbZH0m3GFOlajX83QV+T/X8meE+iyuO/XYjZjnYladt4F79ZA0i4GfvjvaHi9QpcgGJmdPeidhwDGvKO8Q/Lss1k/Y35xjR6qZZ9gGVNFS8XLB93OMJi2p182ecSrzVVt3wUSFY2D/qzxHdUH0gr/1DQVJ0XuIf8uM2O/HvZcO2gOqYthZUweH7ragju3rlhm5HkJ9Kc3NnJd5PAnh7kMsUruK6IIOrz26Z0IXLrKOr6wuf/XbColrjE6IFomIrHr0pOLVvszdbPER09XoezydLSU2NShcP4TjRtWyAY29kXPIq0E3bWim+PGddEg6o9/oYygl8hxF73k6FmGwH4YTU=
  - secure: M1QlJAn735CNsNhMLHj93gAPJhcYOkKKm52NDbTWkZpQLM57xpRLznwjNLazyoo967MCRGBXzbyqzwuD1C81qp0pbthFegQFzSgZ5Vf3OMxN3+c7XWYOarBx1638ab3B6Ybv+PRa5PoQflNPZJH12n0MkhpbqztjVyOjehU2XKJfXTYbiRf4lqsCtA3BbveOldTypliff3aEMqgz9ql6O4ivijjfWCvCAy2oDXrQmXtSgA7KvqvoxkwpvftoUpsNkQe0mZ4cKCyiomq16pZHKBYAkzra3thce7XNhq9OirfKlMDKrSuXko5o00DDYuXcgaFeCERehQmYQmBXgvgWUBuNfiEA/YHE+4yf1vwLznLn8yJ1sm3cvWK4MZg44CoY3pH9iUJWqYxnQqTtltNwvF4ORwd0E8ZH6JoMxIguYNhCeTAjQDksNyLRzC9pb5WSO09Cvj5/V40uDSM20O1S3RnFkt7DDVOk3h2Ami4VxHTJaMMu2oMQ76YNMwB7M7aAXzunOWemzJsd65w8NGGgYHs7z3A/cPfplfrFL55Fx9u99RFoCFv5hHzob0GqsPX21Buw2u6Ll28rhLOY/KbZ10TethlqiWjJ9aj9WsutKA3pCJpMu8ZqwBcdeXYp/raDRHp+N4KwhrH2T4ICO6FOKR+3thRt9CIQYSrVcZT6TgM=
  - secure: qGHoOyWvStQIy0ddCOr9JDc7b3BcELszRoKpNrARQ2EEC8K9Y+TG2LaA/oWI3DIPfAGoGOApDy0ofSkisHbN/VfpyDvxBcEaqA0St262IqwsCspPsRQJdaaG+3hObnDT/aoxb1HAP4Xw9mMsBzTeLrLmHu9iHVvRuUY5DHV/HH2rdzfDWa7GWY5hQSBD06u0hl/F+l3H/eo4O6qB64A7Ejcn1q32pDwNU1buEW528Xv4H4JicG55/IuyM+VW8Ejrl6al0vK+cJpGO/vDrGFr29PDyJDEdg7bmdNc11CwHq+armsbxHBpTUjcIAjNeb5p/Y6H4K3YmFDH3GyJRFLOpaZjyuDlDXccCV57W8iclfm1FTTplX0fO2mOvG5b/BQAIEW0XT2pH4zo8cYUWDSgqs44bGntRMRdH6sIUDJgbb/ZbefFXYhtJNpq4fGtW/TGGJ9TdkgWrR7Gf9HdhDvGJzkrQmiNgKcw7u5zIm8GzYogOpp6pslZXz0ahXUv1So8jgpScjydROITm/sunukRkWk74z7u+2xndnV0q22MzVlfNdI00Sx8Rz7ryCaDpeI8OH1zy6UPkz7/FtSW2u2H4Leq8W2w0rGEPlwByhKxxx+sjFjgDvmH1ZCj7TKNtl31EdHyQgOCEI296pdOwgCyt0jFeBSxDEEWMC3V+Ay33sA=
  matrix:
  - mProc=dev
  - mProc=prod
