sudo: required
dist: trusty
language: node_js
node_js:
- 8.11.1
before_script:
- echo -e "Host fgpv.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- "./scripts/travis/build.sh"
before_install:
- AZ_REPO=$(lsb_release -cs)
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install apt-transport-https azure-cli
cache:
  directories:
  - node_modules
  - features/node_modules
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/travis/deploy-build-azure.sh
  on:
    all_branches: true
- provider: script
  skip_cleanup: true
  script: bash ./scripts/travis/docs.sh
  on:
    all_branches: true
    repo: fgpv-vpgf/fgpv-vpgf
    condition: $TRAVIS_BRANCH =~ ^develop$|^ghpages-docs$|^master$|^v\d
    condition: $mProc == dev
- provider: pages
  target_branch: gh-pages
  local-dir: gh-page-files
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    all_branches: true
    repo: fgpv-vpgf/fgpv-vpgf
    condition: $TRAVIS_BRANCH =~ ^develop$|^ghpages-docs$|^master$|^v\d
    condition: $mProc == dev
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/18575ac051d21e4340b1
    on_success: always
    on_failure: always
    on_start: false
env:
  matrix:
  - mProc=dev
  - mProc=prod
